export const fullUkPostcodeValidatorPattern: RegExp = /(GIR\s0AA)|((([ABCDEFGHIJKLMNOPRSTUWYZ][0-9][0-9]?)|(([ABCDEFGHIJKLMNOPRSTUWYZ][ABCDEFGHKLMNOPQRSTUVWXY][0-9][0-9]?)|(([ABCDEFGHIJKLMNOPRSTUWYZ][0-9][ABCDEFGHJKSTUW])|([ABCDEFGHIJKLMNOPRSTUWYZ][ABCDEFGHKLMNOPQRSTUVWXY][0-9][ABEHMNPRVWXY]))))\s?[0-9][ABDEFGHJLNPQRSTUWXYZ]{2})$/;
export const customerReferencePattern: RegExp = /^\d{9}$/;
