export const mockAppStateFormCompleted = {
  forms: {
    knowledgeCheckQ1: {
      question1: 'Yes',
    },
    knowledgeCheckQ2: {
      question2: 'Yes',
    },
    customerPersonalDetails: {
      title: 'c2044dac-a1eb-48c8-b23c-5255bac96bc0',
      firstName: 'James',
      lastName: 'Bond',
      dob: {
        day: '12',
        month: '12',
        year: '1990',
      },
      profession: 'GENMEDPRAC',
      nationalInsuranceNumber: 'SN 234 234 A',
      nationality: '92',
      addressLookup: {
        postcode: null,
        selectedAddressId: null,
      },
      manualAddress: {
        flatNumber: null,
        houseNumber: '2',
        houseName: null,
        street: 'Baker Street',
        town: 'Lodon',
        region: null,
        county: null,
        postcode: 'SW1 3TS',
      },
      personalEmail: 'alex.cotelin@wesleyan.co.uk',
      personalMobileNumber: '07111222333',
      marketingEmail: null,
      marketingPost: null,
      marketingPhone: true,
    },
    manualAddress: {
      flatNumber: null,
      houseNumber: '2',
      houseName: null,
      street: 'Baker Street',
      town: 'Lodon',
      region: null,
      county: null,
      postcode: 'SW1 3TS',
    },
    investmentOptions: {
      investmentOption: 'MONTHLY_AND_LUMP_SUM',
    },
    lumpSumAndMonthly: {
      totalAmount: {
        lumpSumAmount: '2345',
        monthlyAmount: '345',
      },
      directDebit: {
        accountHolderFullName: 'JB',
        sortCode: {
          c1: '12',
          c2: '12',
          c3: '33',
        },
        accountNumber: '111222',
        bankName: 'BANK',
      },
    },
  },
  attemptId: 1835,
  postcodeLookupAddressList: [],
  currentTaxPeriod: {
    taxPeriodCode: '2020-2021',
    taxPeriodDescription: '2020 to 2021',
    startDateTime: '2020-04-06T00:00:00',
    endDateTime: '2021-04-05T00:00:00',
    lumpSumAccepted: true,
    monthlyPaymentsAccepted: true,
    newISAsAccepted: true,
    topUpsAccepted: true,
    totalAnnualAllowance: 20000,
    minNewLumpSumAmount: 2000,
    minTopUpLumpSumAmount: 1000,
    minNewMonthlyAmount: 250,
    minTopUpMonthlyAmount: 25,
    numberOfMonthlyPayments: 8,
    maxLumpSumAmount: 20000,
    maxMonthlyAmount: 1666.66,
  },
};
